### ISSUE TITLE
上报失败可能是出于什么原因？

### ISSUE THREAD

**Issue by ONLYLOVELYKISS** [icepie/lit-ncov-report#14]

**Comment by ONLYLOVELYKISS** [comment]
就是用腾讯云函数的那种

**Comment by ONLYLOVELYKISS** [comment]
就是用腾讯云函数的那种

**Comment by ONLYLOVELYKISS** [comment]
START RequestId: ea48a9c5-52db-4640-ac00-0c844011fd09Init Report RequestId: ea48a9c5-52db-4640-ac00-0c844011fd09 Coldstart: 3014ms (PullCode: 340ms InitRuntime: 15ms InitFunction: 2659ms) Memory: 512MB MemUsage: 17.38MB上报任务开始执行!
Starting new HTTPS connection (1): sc.ftqq.com:443
https://sc.ftqq.com:443 "GET /SCT88887TbTP5yCGvdIVyE73W98nuQyeR.send?text=%E5%81%A5%E5%BA%B7%E7%8A%B6%E5%86%B5%E7%AE%A1%E6%8E%A7%E5%B9%B3%E5%8F%B0%3A+%E8%BD%AE%E8%AF%A2%E4%BB%BB%E5%8A%A1%E5%87%86%E5%A4%87%E6%89%A7%E8%A1%8C&desp=%09%E6%97%B6%E9%97%B4%3A+2022-03-30+00%3A01%3A03 HTTP/1.1" 200 108
Starting new HTTPS connection (1): sct.ftqq.com:443
https://sct.ftqq.com:443 "GET /SCT88887TbTP5yCGvdIVyE73W98nuQyeR.send?text=%E5%81%A5%E5%BA%B7%E7%8A%B6%E5%86%B5%E7%AE%A1%E6%8E%A7%E5%B9%B3%E5%8F%B0%3A+%E8%BD%AE%E8%AF%A2%E4%BB%BB%E5%8A%A1%E5%87%86%E5%A4%87%E6%89%A7%E8%A1%8C&desp=%09%E6%97%B6%E9%97%B4%3A+2022-03-30+00%3A01%3A03 HTTP/1.1" 404 3491
Starting new HTTP connection (1): hmgr.sec.lit.edu.cn:80
http://hmgr.sec.lit.edu.cn:80 "HEAD /web HTTP/1.1" 301 0
http://hmgr.sec.lit.edu.cn:80 "POST /wms/healthyLogin HTTP/1.1" 200 None
账号:B21050830
Starting new HTTP connection (1): hmgr.sec.lit.edu.cn:80
http://hmgr.sec.lit.edu.cn:80 "HEAD /web HTTP/1.1" 301 0
http://hmgr.sec.lit.edu.cn:80 "POST /wms/healthyLogin HTTP/1.1" 200 None
账号:B21050830
Starting new HTTP connection (1): hmgr.sec.lit.edu.cn:80
http://hmgr.sec.lit.edu.cn:80 "HEAD /web HTTP/1.1" 301 0
http://hmgr.sec.lit.edu.cn:80 "POST /wms/healthyLogin HTTP/1.1" 200 None
账号:B21050830
	上报失败
Starting new HTTPS connection (1): sc.ftqq.com:443
https://sc.ftqq.com:443 "GET /SCT88887TbTP5yCGvdIVyE73W98nuQyeR.send?text=%E5%81%A5%E5%BA%B7%E7%8A%B6%E5%86%B5%E7%AE%A1%E6%8E%A7%E5%B9%B3%E5%8F%B0%3A+%E6%9C%AC%E6%AC%A1%E4%B8%8A%E6%8A%A5%E7%BB%93%E6%9E%9C&desp=%0A%0A%09%E6%80%BB%E5%85%B1%3A+1+%E4%BA%BA%0A%09%E5%A4%B1%E8%B4%A5%3A+1+%E4%BA%BA%0A%09%E7%94%A8%E6%97%B6%3A+1+%E7%A7%92%0A%0A%09%E9%A6%96%E6%AC%A1%3A+0+%E4%BA%BA%0A%09%E4%BA%8C%E6%AC%A1%3A+0+%E4%BA%BA%0A%09%E4%B8%89%E6%AC%A1%3A+0+%E4%BA%BA%0A%09%E6%97%A0%E9%9C%80%3A+0+%E4%BA%BA%0A%0A%0A%E5%A4%B1%E8%B4%A5%E5%88%97%E8%A1%A8%3A+%0A%0A%09B21050830%0A HTTP/1.1" 200 108
Starting new HTTPS connection (1): sct.ftqq.com:443
https://sct.ftqq.com:443 "GET /SCT88887TbTP5yCGvdIVyE73W98nuQyeR.send?text=%E5%81%A5%E5%BA%B7%E7%8A%B6%E5%86%B5%E7%AE%A1%E6%8E%A7%E5%B9%B3%E5%8F%B0%3A+%E6%9C%AC%E6%AC%A1%E4%B8%8A%E6%8A%A5%E7%BB%93%E6%9E%9C&desp=%0A%0A%09%E6%80%BB%E5%85%B1%3A+1+%E4%BA%BA%0A%09%E5%A4%B1%E8%B4%A5%3A+1+%E4%BA%BA%0A%09%E7%94%A8%E6%97%B6%3A+1+%E7%A7%92%0A%0A%09%E9%A6%96%E6%AC%A1%3A+0+%E4%BA%BA%0A%09%E4%BA%8C%E6%AC%A1%3A+0+%E4%BA%BA%0A%09%E4%B8%89%E6%AC%A1%3A+0+%E4%BA%BA%0A%09%E6%97%A0%E9%9C%80%3A+0+%E4%BA%BA%0A%0A%0A%E5%A4%B1%E8%B4%A5%E5%88%97%E8%A1%A8%3A+%0A%0A%09B21050830%0A HTTP/1.1" 404 3491
Response RequestId:ea48a9c5-52db-4640-ac00-0c844011fd09 RetMsg:null
END RequestId:ea48a9c5-52db-4640-ac00-0c844011fd09
Report RequestId:ea48a9c5-52db-4640-ac00-0c844011fd09 Duration:2047ms Memory:512MB MemUsage:18.433594MB
#上面的是日志

**Comment by icepie** [comment]
请固定出口ip
