### ISSUE TITLE
最新打卡一日三次

### ISSUE THREAD

**Issue by Jasoncottom** [icepie/lit-ncov-report#2]
最新的打卡需要一天三次，安排一下呗

**Comment by icepie** [comment]
收到兄弟，准备用go语言重写啦～，大二天天满课，最近太忙了

**Comment by icepie** [comment]
现在其实已经支持三次了( 默认提交昨天的数据, 昨天打卡多少次就是多少次)

**Comment by xuehu96** [comment]
> 收到兄弟，准备用go语言重写啦～，大二天天满课，最近太忙了

Gogogo

**Comment by icepie** [comment]
已在v2分支添加: 67583b68b090423e032fe003dce70e5ada629da8 843c7d18bb6088a329a9e1d9607c016e9187184c
