### ISSUE TITLE
测试出问题

### ISSUE THREAD

**Issue by ONLYLOVELYKISS** [icepie/lit-ncov-report#7]
![image](https://user-images.githubusercontent.com/88222714/139373812-b0e60dfc-81f2-4acf-b808-9eae659d9e69.png)
我又不会整了

**Comment by icepie** [comment]
非本仓库问题，请参考腾讯云 云函数文档

**Comment by ONLYLOVELYKISS** [comment]
妥了，谢谢大佬提点
